### ISSUE TITLE
Goat Lowest and Highest Bid

### ISSUE THREAD

**Issue by dip2397** [71Oliver/StockX-for-Discord#4]
Hello, thanks for a great working bot.

But one issue I have is the lowest and highest bids for GOAT on every product are always $25 and $2000, respectively. 

Thank you

![image](https://user-images.githubusercontent.com/37384254/39685242-1f2c58dc-518f-11e8-897f-b8e644012ab4.png)

Edit: One other thing is in your example picture, I see the sizes listed next to the Sales, Bids, and Ask prices, but I do not see a size listed on mine

**Comment by 71Oliver** [comment]
Hi

Thanks for your comment. Relative sizes have now been added to the Discord embed. I've removed support GOAT for the time being however I am planning on re-adding support for GOAT at a later date.

Thanks
